### ISSUE TITLE
SwipeCardView does not show again when list is repopulated again

### ISSUE THREAD

**Issue by aftabsikander** [Arjun-sna/android-swipecards-view#5]
Hi, I found a strange issue when the collection gets empty by swipe actions. And if we add more into the collection swipeCardView does not appear with update list.

**Comment by phani51** [comment]
Hi Aftab Sikander even i also facing same issue,If u found any solution can u help me..Thanks in advance.

**Comment by aftabsikander** [comment]
@phani51 Yes I have fixed the issue and solved it, I l upload the modified code into my forked version so that you can look how I fixed it, Just to give a understanding issue was fixed when i reset values following field. For this I create a method and it fixed my issue.
```
START_STACK_FROM=0
LAST_OBJECT_IN_STACK=0
MAX_VISIBLE=3
```

**Comment by Arjun-sna** [comment]
fixed the issue in later version 1.0.2
add items to list in adappter and call notifyDatasetChanged() on adapter

**Comment by aftabsikander** [comment]
@Arjun-sna  Alright I will check this update tomorrow and will merge it with my fork as well

**Comment by rkrsgithub** [comment]
@Arjun-sna 

>  **fixed the issue in later version 1.0.2
> add items to list in adappter and call notifyDatasetChanged() on adapter**

Not yet fixed. not working for me...

``@Override
    public void onAdapterAboutToEmpty(int itemsInAdapter) {
        Log.d(TAG, "onAdapterAboutToEmpty() called with: itemsInAdapter = [" + itemsInAdapter + "]");
        if (itemsInAdapter == 1) {
            mArrayAdapter.addAll(getDummyData());
            mArrayAdapter.notifyDataSetChanged();
        }
    }

**Comment by Shubham1209mathur** [comment]
How to fixed this issue?

**Comment by Arjun-sna** [comment]
@Shubham1209mathur @rkrsgithub please check the sample the app provided in the library, where the list is populated and `notifyDataSetChanged()`. It works fine.

`@Override public void onAdapterAboutToEmpty(int itemsInAdapter) {
        getDummyData(al);
        arrayAdapter.notifyDataSetChanged();
      }`

`getDummyData(al)` add more card items to `ArrayList` which is referenced in `ArrayAdapter` and when `notifyDataSetChanged()` is called, it worked.

**Comment by Shubham1209mathur** [comment]
I have already using this.But list is not updating.I have also use the versions 1.2 still facing the issue 

-----Original Message-----

**Comment by vinodsvist252** [comment]
Hi friends i also faced the same issue. After swiping of all crads , again i am getting the data and notifying the adapter but , the cards were not setting and finally i used like this but cards were not calling everytime.But somewhat issue was cleared , nut rarely that issue was coming.I hope that someone will help for this issue.

                                mSwipeView.START_STACK_FROM = 0;
                                mSwipeView.MAX_VISIBLE = 1;
                                mSwipeView.LAST_OBJECT_IN_STACK = 0;
                                mSwipeView.MIN_ADAPTER_STACK = 6;

**Comment by sohanshetty** [comment]
hi 
adapter is not upating with  new data showing empty view always please help me
